language: nodejs
node_js:
  - "8"
dist: xenial
sudo: required
addons:
  apt:
    packages:
    - gcc
    - g++
    - nodejs
script:
  - nvm install 8
  - npm install
  - webpack --config webpack.prod.config.js
